version: 2.1
jobs:
  test:
    docker:
      - image: mcr.microsoft.com/playwright:v1.51.0-jammy
    steps:
      - checkout
      - run: npm install
      - run: npx playwright install --with-deps
      - run: npx playwright test

workflows:
  version: 2
  validate:
    jobs:
      - test